services:
- mongodb
notifications:
  email: false
  flowdock:
    secure: H/xqLJ9qDlH40UWf09861FECGgDYg1n8b2jpJ16heVK4IuLrPOtWJGzreuDq9WQy/ISXuJwc47Jp5oAVp4D54n403/nupru33VYbSXiDKC+3/qjzMH8phSBMiz0X05/lZPimRA1zfN98waQTS8hB0fCpbih5JpO/UBTu4kOcjL0=
env:
  global:
  - secure: gGxojZCjflhmCNL4ElvLExUGvhzqaLBwRnyXzga+TggE9u3AELGZZFmYbj1wnR1iuXMuOn4+KtzOt2EDAKQZbEQ+vyR05MgyjNu0Qjncr7066BvcHh9HpV5ZSiKrs2ekMFYEyJelhpmV+4kdj+OdTo1b1Vtg7QZmjroFO67bH88=
  - secure: byACiHmQfIahKXf3oBA2Odkukg31as0AkVhdvd/ltKHFM8ptbhEmSfY3NooLModETsVCCHnoZXdlGHSzpgEX8Obj8fJig2vTGHfZmWIjWce+BlPw33eUB5mYaK8bymsDet3w4O46/Zsu/53o7diqWzRjlcOr1Bwhf01FtHlShBw=
  - secure: ez3d4kiKejNvh0hGva1yTVsPVPJnj4ZEmMHp6j02e/B5jXskyEpI9PvWxv5LbTROibvtK3Z9j86Qf38tr/XW6H9e6VY08cm2BCJ85LreTDx9JMWQo2FQDCC6Czw229+g/RusuQ1wN0RdYWLFVgFkhJ7kao8oJVSnajJUf5ij33s=
  - secure: oq06svGtfBTnGFVg+TtgEOKBldWliHOVEEbS/icBFfuuYEp3xGPJU+RuJBNVbsT9RMuZ4y/od27oRfTRjs4j8RpWyuAPupYQGj6l8HJeGN2RCsfRyU8CC3RogvPsiAEhEv4Rr7P35+afnxnBwsOfTtNlt3Iw0DooNoYLldE+UCw=
